theme: minima
title: "Ahmad's corner"
author: Ahmad Abdullah
email: ahmadnofly@hmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Hello there. It's me trying my hand in carving a space in the digital world. My thoughts are my own.

# social links
twitter_username: ahmad_znz # DO NOT include the @ character, or else the build will fail!
github_username:  ahmad1284 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
