theme: minima
title: "Ahmad's corner"
author: Ahmad Abdullah
email: ahmadnofly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello there. It's me trying my hand in carving a space in the digital world. My thoughts are my own.

# social links
twitter_username: ahmad_znz # DO NOT include the @ character, or else the build will fail!
github_username:  ahmad1284 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
